/**
 * Writes docs/reference/live-schema.md from the databases themselves.
 *
 *   npm run db:snapshot
 *
 * The repository cannot rebuild the database — `profiles`, `connections`,
 * `notifications` and `photo_access` are created by no migration, and
 * `match_guna_scores` is declared by one but exists nowhere. So the migrations
 * do not describe the schema, and writing SQL against them produces columns
 * that do not exist.
 *
 * That has now cost two failed migrations: `shortlists.shortlisted_by`, copied
 * from a migration that references it although it was never created, and
 * `notifications.title`/`.message`, which silently swallowed every membership
 * expiry notice.
 *
 * This is not a substitute for a real `pg_dump` baseline — it captures columns
 * and types, not constraints, indexes, policies or triggers. It is a reference
 * to check against before writing SQL, generated from what is actually there.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const OUT = "docs/reference/live-schema.md";

function readEnv(file) {
  const out = {};
  try {
    for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
      const m = line.trim().match(/^([A-Z0-9_]+)=(.*)$/);
      if (m) out[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
    }
  } catch {
    /* file may not exist */
  }
  return out;
}

async function introspect(env) {
  const url = env.NEXT_PUBLIC_SUPABASE_URL;
  const key = env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) return null;

  const res = await fetch(`${url}/rest/v1/`, {
    headers: { apikey: key, Authorization: `Bearer ${key}` },
  });
  if (!res.ok) return null;

  const spec = await res.json();
  const tables = {};
  for (const [name, def] of Object.entries(spec.definitions ?? {})) {
    tables[name] = Object.entries(def.properties ?? {}).map(([col, meta]) => ({
      name: col,
      type: meta.format ?? meta.type ?? "?",
      required: (def.required ?? []).includes(col),
    }));
  }
  return { ref: url.replace("https://", "").split(".")[0], tables };
}

const dev = await introspect(readEnv(".env.development.local"));
const prod = await introspect(readEnv(".env.local"));

if (!dev) {
  console.error("Could not reach the dev database.");
  process.exit(1);
}

const lines = [
  "# Live schema",
  "",
  "Generated by `npm run db:snapshot` from the databases themselves, because the",
  "migrations in this repository do not describe them — several tables, including",
  "`profiles`, are created by no migration at all.",
  "",
  "**Check column names here before writing SQL.** Two migrations have already",
  "failed on columns that exist only in an old migration file.",
  "",
  "Columns and types only. Constraints, indexes, policies and triggers are not",
  "captured; a real `pg_dump` baseline is still outstanding.",
  "",
  `Dev: \`${dev.ref}\`${prod ? ` · Production: \`${prod.ref}\`` : " · production not reachable from here"}`,
  "",
];

const names = [...new Set([...Object.keys(dev.tables), ...Object.keys(prod?.tables ?? {})])].sort();

for (const table of names) {
  const devCols = dev.tables[table];
  const prodCols = prod?.tables?.[table];

  lines.push(`## ${table}`, "");

  if (!devCols) {
    lines.push("_Production only — absent from dev._", "");
  } else if (prod && !prodCols) {
    lines.push("_Dev only — absent from production._", "");
  }

  const cols = devCols ?? prodCols ?? [];
  const devNames = new Set((devCols ?? []).map((c) => c.name));
  const prodNames = new Set((prodCols ?? []).map((c) => c.name));

  lines.push("| Column | Type | Required |", "| --- | --- | --- |");
  for (const col of cols) {
    const onlyIn =
      prod && devNames.has(col.name) && !prodNames.has(col.name)
        ? " _(dev only)_"
        : prod && !devNames.has(col.name) && prodNames.has(col.name)
          ? " _(prod only)_"
          : "";
    lines.push(`| \`${col.name}\`${onlyIn} | ${col.type} | ${col.required ? "yes" : ""} |`);
  }
  lines.push("");
}

mkdirSync("docs/reference", { recursive: true });
writeFileSync(OUT, lines.join("\n"), "utf8");

console.log(`Wrote ${OUT}`);
console.log(`  ${names.length} tables`);
if (prod) {
  const devOnly = names.filter((t) => dev.tables[t] && !prod.tables[t]);
  const prodOnly = names.filter((t) => !dev.tables[t] && prod.tables[t]);
  if (devOnly.length) console.log(`  dev only:  ${devOnly.join(", ")}`);
  if (prodOnly.length) console.log(`  prod only: ${prodOnly.join(", ")}`);
  if (!devOnly.length && !prodOnly.length) console.log("  dev and production agree");
}
